Document: qt-web-app
Title: Debian qt-web-app Manual
Author: <insert document author here>
Abstract: This manual describes what qt-web-app is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qt-web-app/qt-web-app.sgml.gz

Format: postscript
Files: /usr/share/doc/qt-web-app/qt-web-app.ps.gz

Format: text
Files: /usr/share/doc/qt-web-app/qt-web-app.text.gz

Format: HTML
Index: /usr/share/doc/qt-web-app/html/index.html
Files: /usr/share/doc/qt-web-app/html/*.html
